config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :destroy]
  after_action :handle_jsonp, only: :show
  around_action :catch_errors_for_jsonp, only: :show

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # We call set_group() here instead of before_action because we
    # want it wrapped in around_action, so that any exceptions that it
    # may generate are also caught (for JSONP calls).
    set_group
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between
    # actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the
    # white list through.
    def group_params
      params.require(:group).permit(:name, :balance, :private)
    end

    def handle_jsonp
      return unless request.format == :json and params[:callback]
      response['Content-Type'] = 'application/javascript'
      response.body = "#{params[:callback]}(#{response.body});"
    end

    def catch_errors_for_jsonp
      if request.format != :json or not params[:callback]
        # We only wrap JSONP calls; bail out.
        yield
        return
      end

      begin
        yield
      rescue ActiveRecord::RecordNotFound => e
        render json: {status: :not_found, error: e.message}, status: :ok
      rescue
        render json: {status: :internal_server_error, error: 'Unknown error'}, status: :ok
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_html.html.erb
<% html_text = <<END
  <p>
    Name: <span id="name-chimp-#{group.id}"></span><br />
    Balance: <span id="balance-chimp-#{group.id}"></span>
  </p>
  <script>
    if(typeof window.console == 'undefined') {
        window.console = {log: function (msg) {}};
    }
    function groupCallback(data) {
      if(data.hasOwnProperty('error')) {
        alert('An error occurred while trying to retrieve group data.');
        console.log('Server error: ' + data.error);
        throw 'Unexpected error';
      }
      document.getElementById("name-chimp-#{group.id}").innerHTML = data.name;
      document.getElementById("balance-chimp-#{group.id}").innerHTML = data.balance;
    }
  </script>
  <script src="#{request.protocol}#{request.host_with_port}/groups/#{group.id}.json?callback=groupCallback"></script>
END
%>

<a href="#" role="button" class="btn-link no-outline" data-toggle="modal" data-target="#group-<%= group.id %>-html">HTML</a>

<!-- Modal -->
<div class="modal fade" id="group-<%= group.id %>-html" tabindex="-1" role="dialog" aria-labelledby="group-<%= group.id %>-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="group-<%= group.id %>-html">HTML code to copy</h4>
      </div>
      <div class="modal-body">
        <%= html_text %>
      </div>
      <div class="modal-footer">
        <a href="#" role="button" class="btn-link" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Balance</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= group.name %></td>
        <td><%= group.balance %></td>
        <td><input type="checkbox" disabled <%= "checked" if group.private %>></td>
        <td><%= render 'html', group: group %></td>
        <td><%= link_to('Edit', edit_group_path(group)) %></td>
        <td><%= link_to('Delete', group, method: :delete, data: {confirm: 'Are you sure?'}) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_group_path do %>
  <i class="glyphicon glyphicon-plus"></i> New Group
<% end %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @group.balance %>
</p>

<p>
  <strong>Private:</strong>
  <%= @group.private %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ror</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-2">
      </div>
      <div class="col-xs-8">
        <%= yield %>
      </div>
      <div class="col-xs-2">
      </div>
    </div>
  </div>
</body>
</html>